add option -r --remove --clear in the command git alias

diff --git a/bin/git-alias b/bin/git-alias
--- a/bin/git-alias
+++ b/bin/git-alias
@@ -19,22 +19,52 @@ if [[ "$1" == "--local" || "$1" == "--global" ]]; then
     shift
 fi
 
-case $# in
-  0)
+
+if [ "$1" == "--remove-all" ] || [ "$1" == "--clear" ]; then
+    # all,the alis
+    aliases=$(git config $options --get-regexp '^alias\.' 2>/dev/null | awk '{print $1}')
+    if [[ -z "$aliases" ]]; then
+        >&2 echo "No aliases to remove."
+        exit 1
+    fi  #remove all
+    for a in $aliases; do
+        git config $options --unset "$a"
+    done
+    shift
+elif [ "$1" == "--remove" ] || [ "$1" == "-r" ]; then
+    # remot one alias named
+    if [[ -z "$2" ]]; then
+        >&2 echo "Error: missing alias name."
+        exit 1
+    fi
+    if git config $options --get alias."$2" >/dev/null 2>&1; then   #if no options ,test it
+        git config $options --unset alias."$2"
+    else
+        >&2 echo "Error: alias '$2' does not exist."
+        exit 1
+    fi
+    shift 2
+fi
+
+
+
+# so $1 is --global or --local
+case "$#" in
+  0)  # no args after --globak/local --> all the alias
       if [[ -z "$options" ]]; then
         git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
       else
         git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort
       fi
       ;;
-  1)
+  1)  #one arg after  --global/--local --> searhc the alias of one name 
       if [[ -z "$options" ]]; then
         git config --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
       else
         git config "$options" --get-regexp 'alias.*' | sed 's/^alias\.//' | sed 's/[ ]/ = /' | sort | grep -e "$1"
       fi
       ;;
-  2)
+  2)  #like --global alias.st status  --> 2 arguments = create an alias
       if [[ -z "$options" ]]; then
         git config alias."$1" "$2"
       else
